### ISSUE TITLE
LeanCache 相关操作使用 cookies 鉴权

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#102]

**Comment by sdjcw** [comment]
LeanCache 服务端现在还不支持 cookies 鉴权，等待 https://github.com/leancloud/cloud-code/issues/980

**Comment by aisk** [comment]
这个好像还没完成吧？

**Comment by jysperm** [comment]
和 cloud-code#980 这个内容是一样的

**Comment by jysperm** [comment]
好吧，是不同的仓库 ....

**Comment by jysperm** [comment]
已在 https://github.com/leancloud/lean-cli/pull/443 实现
