### ISSUE TITLE
使用lean deploy部署java war 时，发生异常

### ISSUE THREAD

**Issue by DavyLin** [leancloud/lean-cli#106]
➜  /Volumes/HDD/work/ideaprojects/leancloud/record  >lean deploy
> 获取应用信息 [SUCCESS]
> 准备部署至目标应用：**** (*********)
> 获取应用分组信息 [SUCCESS]
> 准备部署应用到预备环境
> 检测到 Java 运行时
> 压缩项目文件 ... [SUCCESS]
> 上传应用文件 30.13 MB / 35.27 MB [=============================>-----]  85.41% 1m49s
panic: invalid character '<' looking for beginning of value [recovered]
	panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
panic(0x3c8800, 0xc4203ba5a0)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli.HandleAction.func1(0xc420a63880)
	/private/tmp/lean-cli-20160908-55187-x0qc2a/lean-cli-0.2.1/src/github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli/app.go:478 +0x247
panic(0x3c8800, 0xc4203ba5a0)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:458 +0x243
github.com/leancloud/lean-cli/lean/api.NewErrorFromBody(0xc420122f00, 0x2d3, 0x2d3, 0xc421374900)
	/private/tmp/lean-cli-20160908-55187-x0qc2a/lean-cli-0.2.1/src/github.com/leancloud/lean-cli/lean/api/error.go:30 +0x163
github.com/leancloud/lean-cli/lean/api.UploadFile(0xc42007b320, 0x21, 0xc4202eb260, 0x53, 0x895a, 0x9600, 0x4)
	/private/tmp/lean-cli-20160908-55187-x0qc2a/lean-cli-0.2.1/src/github.com/leancloud/lean-cli/lean/api/file.go:62 +0x653
main.uploadProject(0xc42007b320, 0x21, 0x43c15c, 0x1, 0xc42016d360, 0x65407, 0x616f60)
	/private/tmp/lean-cli-20160908-55187-x0qc2a/lean-cli-0.2.1/src/github.com/leancloud/lean-cli/lean/deploy_action.go:89 +0x28a
main.deployFromLocal(0xc42007b320, 0x21, 0xc4204063b8, 0x7, 0x0, 0x0)
	/private/tmp/lean-cli-20160908-55187-x0qc2a/lean-cli-0.2.1/src/github.com/leancloud/lean-cli/lean/deploy_action.go:98 +0x6c
main.deployAction(0xc4200c2640, 0x0, 0x0)
	/private/tmp/lean-cli-20160908-55187-x0qc2a/lean-cli-0.2.1/src/github.com/leancloud/lean-cli/lean/deploy_action.go:166 +0x2a8
reflect.Value.call(0x3bdba0, 0x47cd18, 0x13, 0x43c8fd, 0x4, 0xc420a63840, 0x1, 0x1, 0x77738, 0x430da0, ...)
	/usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x3bdba0, 0x47cd18, 0x13, 0xc420a63840, 0x1, 0x1, 0x643940, 0xc42004d890, 0x80166)
	/usr/local/Cellar/go/1.7/libexec/src/reflect/value.go:302 +0xa4
github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli.HandleAction(0x3bdba0, 0x47cd18, 0xc4200c2640, 0x0, 0x0)
	/private/tmp/lean-cli-20160908-55187-x0qc2a/lean-cli-0.2.1/src/github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli/app.go:487 +0x1e0
github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli.Command.Run(0x43d5f8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x448b31, 0x21, 0x0, ...)
	/private/tmp/lean-cli-20160908-55187-x0qc2a/lean-cli-0.2.1/src/github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli/command.go:186 +0xc2b
github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli.(*App).Run(0xc420126000, 0xc420090060, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/lean-cli-20160908-55187-x0qc2a/lean-cli-0.2.1/src/github.com/leancloud/lean-cli/lean/vendor/github.com/codegangsta/cli/app.go:240 +0x611
main.main()
	/private/tmp/lean-cli-20160908-55187-x0qc2a/lean-cli-0.2.1/src/github.com/leancloud/lean-cli/lean/main.go:134 +0x587

**Comment by aisk** [comment]
您好，这个可能是网络原因导致报错失败了。另外您项目文件压缩之后有三十多M，增大了传输失败的可能，可以排查下是不是把不需要的文件也打包上传了。

**Comment by aisk** [comment]
您好，我又继续测试了一下，发现目前使用的上传文件的接口暂时最大只支持 30M，详情参考：#31

目前麻烦您直接把代码上传到 git 仓库，在控制台上使用 git 的方式进行部署。

**Comment by DavyLin** [comment]
了解了，谢谢：）

**Comment by DavyLin** [comment]
你好，我优化了下项目，小于30m了，然后上传后，一直卡在下载依赖这边。。。这个问题，需要怎么解决。。快有20分钟了，照理说，应该下载依赖挺快的吧！在 2016年9月18日，11:14，Long Ang <notifications@github.com> 写道：您好，我又继续测试了一下，发现目前使用的上传文件的接口暂时最大只支持 30M，详情参考：#31目前麻烦您直接把代码上传到 git 仓库，在控制台上使用 git 的方式进行部署。—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/leancloud/lean-cli","title":"leancloud/lean-cli","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/leancloud/lean-cli" class="">https://github.com/leancloud/lean-cli</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aisk in #106: 您好，我又继续测试了一下，发现目前使用的上传文件的接口暂时最大只支持 30M，详情参考：#31\r\n\r\n目前麻烦您直接把代码上传到 git 仓库，在控制台上使用 git 的方式进行部署。"}],"action":{"name":"View Issue","url":"<a href="https://github.com/leancloud/lean-cli/issues/106#issuecomment-247822174" class="">https://github.com/leancloud/lean-cli/issues/106#issuecomment-247822174</a>"}}}

**Comment by DavyLin** [comment]
目前我又试了两次，有错误提示，是这样的：

**Comment by aisk** [comment]
回复的格式好像有些问题，我没看到出错的提示，能重新发一下吗？

**Comment by DavyLin** [comment]
我刚才共试了两次，提示如下:
➜  /Volumes/HDD/work/ideaprojects/fhedu/record git:(record-mvn) ✗ >lean deploy
> 获取应用信息 [SUCCESS]
> 准备部署至目标应用：******* (*******************)
> 获取应用分组信息 [SUCCESS]
> 准备部署应用到预备环境
> 检测到 Java 运行时
> 压缩项目文件 ... [SUCCESS]
> 上传应用文件 28.51 MB / 28.51 MB [===================================] 100.00% 1m51s
> 开始构建 20160918-123803 [SUCCESS]
> 正在下载应用代码 ... [SUCCESS]
> 正在解压缩应用代码 ... [SUCCESS]
> 运行环境: java-war (leanengine/java-war-base-8) [SUCCESS]
> 正在下载和安装依赖项 ... ...删除临时文件 [FAIL]
> Get https://leancloud.cn/1.1/engine/events/poll/1474173483974?from=2016-09-18T04:38:39.561Z: net/http: TLS handshake timeout
➜  /Volumes/HDD/work/ideaprojects/fhedu/record git:(record-mvn) ✗ >
➜  /Volumes/HDD/work/ideaprojects/fhedu/record git:(record-mvn) ✗ >
➜  /Volumes/HDD/work/ideaprojects/fhedu/record git:(record-mvn) ✗ >
➜  /Volumes/HDD/work/ideaprojects/fhedu/record git:(record-mvn) ✗ >lean deploy
> 获取应用信息 [SUCCESS]
> 准备部署至目标应用：******* (********************)
> 获取应用分组信息 [SUCCESS]
> 准备部署应用到预备环境
> 检测到 Java 运行时
> 压缩项目文件 ... [SUCCESS]
> 上传应用文件 28.51 MB / 28.51 MB [===================================] 100.00% 1m49s
> 开始构建 20160918-132216 [SUCCESS]
> 正在下载应用代码 ... [SUCCESS]
> 正在解压缩应用代码 ... [SUCCESS]
> 运行环境: java-war (leanengine/java-war-base-8) [SUCCESS]
> 正在下载和安装依赖项 ... ...> 删除临时文件 [SUCCESS]
> http: read on closed response body

**Comment by aisk** [comment]
不好意思，这个是抓取日志的时候出错了，实际部署未必已经中断，可以去控制台的日志看一下最终结果。

**Comment by DavyLin** [comment]
我在控制台日志中看了下，这个是启动失败了吗？能知道什么原因吗？
日志：

开始构建 20160918-123803
INFO 正在下载应用代码 ...
INFO 正在解压缩应用代码 ...
INFO 运行环境: java-war (leanengine/java-war-base-8)
INFO 正在下载和安装依赖项 ...
INFO 开始构建 20160918-132216
INFO 正在下载应用代码 ...
INFO 正在解压缩应用代码 ...
INFO 运行环境: java-war (leanengine/java-war-base-8)
INFO 正在下载和安装依赖项 ...
ERROR 2016-09-18 15:39:51.309:INFO::main: Logging initialized @1041ms
ERROR 2016-09-18 15:39:52.030:INFO:oejs.SetUIDListener:main: Setting umask=02
ERROR 2016-09-18 15:39:52.419:INFO:oejs.SetUIDListener:main: Opened ServerConnector@6bf256fa{HTTP/1.1,[http/1.1]}{0.0.0.0:3000}
ERROR 2016-09-18 15:39:52.419:INFO:oejs.SetUIDListener:main: Setting GID=999
ERROR 2016-09-18 15:39:52.421:INFO:oejs.SetUIDListener:main: Setting UID=2001
ERROR 2016-09-18 15:39:52.424:INFO:oejs.Server:main: jetty-9.3.10.v20160621
ERROR 2016-09-18 15:39:52.445:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/] at interval 1
INFO [main] INFO  AppInitListener - LeanEngine app init.
ERROR 2016-09-18 15:40:00.010:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@56ac3a89{/,file:///var/lib/jetty/webapps/ROOT/,AVAILABLE}{/ROOT}
ERROR 2016-09-18 15:40:00.026:INFO:oejs.AbstractConnector:main: Started ServerConnector@6bf256fa{HTTP/1.1,[http/1.1]}{0.0.0.0:3000}
ERROR 2016-09-18 15:40:00.027:INFO:oejs.Server:main: Started @9760ms

**Comment by aisk** [comment]
看上去应该是成功了，麻烦您直接访问一下试试。

**Comment by DavyLin** [comment]
我昨天使用你们的模板项目部署了一份，现在访问的还是模板项目，自己的项目没有启动起来，里面这些ERROR错误是什么意思？

**Comment by aisk** [comment]
这里是 Java 的默认日志处理会把日志打印到 stderr 上，在控制台或者命令行工具会按照 ERROR 展示。我们后续会修改一下这个逻辑，实在不好意思……

**Comment by DavyLin** [comment]
我以为这些是错误日志，我再部署一次看下，如果还有问题，我再反馈到这边，谢谢：）

**Comment by DavyLin** [comment]
我又试了下，还是不行，控制台显示 预备环境 部署的最新时间是  一天前  ，即昨天的模板项目:(

**Comment by aisk** [comment]
如果方便的话，可以把 app ID 发到我的邮箱中： lan@leancloud.rocks

**Comment by DavyLin** [comment]
已发到你邮箱，谢谢帮忙查看！

**Comment by aisk** [comment]
我看到您应用设置了很多 `LEANCLOUD_` 开头的环境变量，这几个应该是您自己添加的。LeanEngine 默认会有这些环境变量，请不要尝试自己设置，麻烦删除掉这几个环境变量重试一下。

**Comment by DavyLin** [comment]
噢，好的，我试试看，原来是看文档才设置了那几个，以为这几个需要自己设置啊。https://leancloud.cn/docs/leanengine_webhosting_guide-java.html#环境变量

晕了..

**Comment by DavyLin** [comment]
发现每次等待  下载和安装依赖  需要花好多时间！差不多前后有30分钟左右，目前还是旧的状态，没有部署上去，没有提示 实例部署成功！继续等待看看

**Comment by aisk** [comment]
我刚才测试了一个使用命令行工具创建的 Java 项目，没有任何修改的情况下用了一分钟就部署完成了。您是添加过什么依赖吗？

**Comment by DavyLin** [comment]
是这样的，我使用模板创建的，也是只要2分钟左右就完成部署了，我原来的项目是使用spring 框架直接调用 rest api的，后面推出java 云引擎后，就把这个改造过来了，主要有依赖spring 的一些包，以及其他第三方的一些包资源。。
关于这个问题，我还想问下，是不是jar只有在你们的nexus服务中才可以下载下来，如果你们的nexus服务没有该jar包，会下载失败吗？

**Comment by aisk** [comment]
@sdjcw

**Comment by DavyLin** [comment]
每次部署都是到这里了，然后就没有了。。

INFO  18:52:26 开始构建 20160918-185226
INFO  18:52:26 正在下载应用代码 ...
INFO  18:52:36 正在解压缩应用代码 ...
INFO  18:53:15 运行环境: java-war (leanengine/java-war-base-8)
INFO  18:53:15 正在下载和安装依赖项 ...
INFO staging1 20:41:26 [main] INFO  AppInitListener - LeanEngine app init.

下载 和安装依赖这个，花了快2个小时，刚才这下有点夸张啊。。感觉快要有点想放弃了。。

**Comment by sdjcw** [comment]
你好，我们最近会改进下依赖缓存的方式，应该可以加快部署速度。

**Comment by DavyLin** [comment]
@sdjcw 依赖慢只是另一个问题，但是现在部署还未成功过，不知道是我的项目问题，还是依赖导致的，目前还无法使用，我可能只能再买个阿里云服务器，使用普通的部署方式先用着了，使用阿里云主要担心访问到你们的网络速度问题！但可能也是当下的无奈之举了。。

**Comment by DavyLin** [comment]
刚才重新整理了下依赖的jar ，又重新试了一次，报出如下提示：
> 获取应用信息 [SUCCESS]
> 准备部署至目标应用：******* (**********************)
> 获取应用分组信息 [SUCCESS]
> 准备部署应用到预备环境
> 检测到 Java 运行时
> 压缩项目文件 ... [SUCCESS]
> 上传应用文件 28.52 MB / 28.52 MB [===================================] 100.00% 1m54s
> 服务器内部错误，如有疑问请从帮助菜单进入社区提交问题，内部错误代码: RWryYQbt

**Comment by DavyLin** [comment]
昨天通过git源码部署了，还是卡在这里，能否帮忙看下后台是什么原因：

INFO  2016-09-18 23:01:19 开始构建 20160918-230119
INFO  2016-09-18 23:01:20 正在克隆应用代码 ...
INFO  2016-09-18 23:01:25 运行环境: java-war (leanengine/java-war-base-8)
INFO  2016-09-18 23:01:25 跳过依赖缓存
INFO  2016-09-18 23:01:26 正在下载和安装依赖项 ...

**Comment by DavyLin** [comment]
@sdjcw 我现在本地lean up都没有问题，现在无论什么方式，命令行工具部署或者源码部署，都是卡在下载和安装依赖这边，能看看什么原因吗？如何解决？

**Comment by sdjcw** [comment]
你好，我正在优化依赖缓存缓解，预计今天可以上线。
很抱歉给你带来这么糟糕的体验。

**Comment by DavyLin** [comment]
好的，我今天暂时切换到阿里云了，这块上线了，告诉我下，我再切过来！

**Comment by sdjcw** [comment]
你好，我修改了 maven 的源，下载依赖包的速度应该会快一些。你可以尝试下。

顺便提醒下，Java 运行环境相对比较消耗内存，所以默认的免费实例（256MB 内存）很可能启动起来就会 OOM，导致启动检测失败。所以建议升级到 512MB 以上的规格。

**Comment by DavyLin** [comment]
好的，我试下，我之前就考虑到了，已经升级到512MB了，如果部署成功，我后面再升级到1G内存的规格

**Comment by DavyLin** [comment]
@sdjcw 我从昨晚开始构建 ，早上起来看了下，还是停在加载依赖这步了，是否是我的项目打包有问题呢？日志显示如下：
INFO  2016-09-19 22:54:24 开始构建 20160919-225424
INFO  2016-09-19 22:54:24 正在克隆应用代码 ...
INFO  2016-09-19 22:54:31 运行环境: java-war (leanengine/java-war-base-8)
INFO  2016-09-19 22:54:31 跳过依赖缓存
INFO  2016-09-19 22:54:31 正在下载和安装依赖项 ...

**Comment by jwfing** [comment]
现在是不是 maven 源被固定死了？从昨天下午开始，项目 deploy 时一直报无法解决依赖。。。
1, pom.xml

```
    <repository>
      <id>org.jenkins-ci</id>
      <name>jenkins-ci</name>
      <url>http://repo.jenkins-ci.org/public</url>
    </repository>
```

2, lean deploy 的时候一直报：

```
> 部署失败：[ERROR] Failed to execute goal on project gitrac: Could not resolve dependencies for project cn.leancloud.gitrac:gitrac:war:0.0.1-SNAPSHOT: Failed to collect dependencies at org.kohsuke:github-api:jar:1.77 -> com.infradna.tool:bridge-method-annotation:jar:1.14 -> org.jenkins-ci:annotation-indexer:jar:1.4: Failed to read artifact descriptor for org.jenkins-ci:annotation-indexer:jar:1.4: Could not find artifact org.jenkins-ci:jenkins:pom:1.26 in leancloud (http://mvn.leancloud.cn/nexus/content/groups/public/)
```

3, 本地 mvn compile 时会显示如下信息：

```
Downloading: http://repo.jenkins-ci.org/public/org/jenkins-ci/annotation-indexer/1.4/annotation-indexer-1.4.pom
Downloaded: http://repo.jenkins-ci.org/public/org/jenkins-ci/annotation-indexer/1.4/annotation-indexer-1.4.pom (2 KB at 0.8 KB/sec)
Downloading: http://repo.jenkins-ci.org/public/org/jenkins-ci/jenkins/1.26/jenkins-1.26.pom
Downloaded: http://repo.jenkins-ci.org/public/org/jenkins-ci/jenkins/1.26/jenkins-1.26.pom (27 KB at 24.9 KB/sec)
```

**Comment by sdjcw** [comment]
@jwfing 是我们的仓库和中央仓库不同步造成的。现在正在处理，同步完应该就好了。

**Comment by DavyLin** [comment]
@sdjcw hi，现在java 云引擎这个问题，解决了吗？

**Comment by sdjcw** [comment]
你好，几天前已经解决了，你可以再尝试下。

**Comment by sdjcw** [comment]
不过注意下如果项目中配置了 leancloud 的 mvn 源，需要变更下， 具体变更可以参考这个 commit https://github.com/leancloud/java-war-getting-started/commit/ffc13c6be7bb4aed35d6356c1f6566690862827f

**Comment by DavyLin** [comment]
@sdjcw ，如果项目中配置了其他mvn源，是否可以，比如这样：
                 <repository>
			<id>centralrepo</id>
			<name>CentralRepo</name>
			<url>http://central.maven.org/maven2/</url>
		</repository>
		<repository>
			<id>apacherepo</id>
			<name>ApacheRepo</name>
			<url>http://repo.maven.apache.org/maven2/</url>
		</repository>

**Comment by sdjcw** [comment]
第一个源不需要配置，因为默认就是这个源。第二个应该也不用配置，好像是可以自己找到的。

**Comment by DavyLin** [comment]
@sdjcw 我改了mvc源了，然后我的项目里面有还其他源
                 `<repository>`
			`<id>leancloud</id>`
			`<name>LeanCloud</name>`
			`<url>http://mvn.leancloud.cn/nexus/content/groups/public/</url>`
		`</repository>`
		`<repository>`
			`<id>spring-milestone</id>`
			`<url>https://repo.spring.io/libs-milestone</url>`
		`</repository>`
		`<repository>`
			`<snapshots><enabled>true</enabled></snapshots>`
			`<id>repository.spring.snapshot</id>`
			`<name>Spring  Snapshot  Repository</name>`
			`<url>http://repo.spring.io/snapshot</url>`
		`</repository>`
目前还是停留在这里：
```
INFO  2016-09-26 15:33:57 开始构建 20160926-153357
INFO  2016-09-26 15:33:57 正在克隆应用代码 ...
INFO  2016-09-26 15:34:04 运行环境: java-war (leanengine/java-war-base-8)
INFO  2016-09-26 15:34:04 跳过依赖缓存
INFO  2016-09-26 15:34:04 正在下载和安装依赖项 ...
```
这个会是什么原因，我有使用spring等其他第三方包，不会是云引擎资源不够吧，目前是1cpu,512的

**Comment by sdjcw** [comment]
麻烦把你的 pom.xml 给我一份，我试试看。

**Comment by DavyLin** [comment]
@sdjcw 怎么发给你，邮箱是？

**Comment by sdjcw** [comment]
不用发了，我从服务器上找下。

**Comment by sdjcw** [comment]
找到一处卡住的地方，我们改善下。

**Comment by DavyLin** [comment]
thank you

**Comment by DavyLin** [comment]
@sdjcw 解决好了，通知下

**Comment by sdjcw** [comment]
你好，我测试已经可以了，麻烦你再试试看。

**Comment by DavyLin** [comment]
@sdjcw 你测试花了多久时间 ，我15分钟过去了，还是下载依赖中，不会是我的实例资源不够吧。。

**Comment by sdjcw** [comment]
```
2016-09-23 15:58:17 [INFO] 开始构建 20160923-155817
2016-09-23 15:58:17 [INFO] 正在下载应用代码 ...
2016-09-23 15:58:18 [INFO] 正在解压缩应用代码 ...
2016-09-23 15:58:18 [INFO] 运行环境: java-war (leanengine/java-war-base-8)
2016-09-23 15:58:18 [INFO] 正在下载和安装依赖项 ...
2016-09-23 15:58:46 [INFO] 存储镜像到仓库 ...
2016-09-23 15:58:49 [INFO] 镜像构建完成：20160923-155817
2016-09-23 15:58:49 [INFO] 开始部署 20160923-155817 到 web1
2016-09-23 15:58:49 [INFO] 正在创建新实例 ...
2016-09-23 15:58:49 [INFO] 正在启动新实例 ...
2016-09-23 15:59:15 [INFO] 实例启动成功：LeanEngine
2016-09-23 15:59:16 [INFO] 正在统一切换新旧实例 ...
2016-09-23 15:59:16 [INFO] 正在更新云函数信息 ...
2016-09-23 15:59:16 [INFO] 部署完成：1 个实例部署成功
```

**Comment by sdjcw** [comment]
你好，确认是不分部署服务器部署脚本没有同步，我操作下。

**Comment by DavyLin** [comment]
@sdjcw 我还是无法成功部署，能查下卡在哪里吗？目前部署的是预备环境，是否预备环境还有问题？

**Comment by sdjcw** [comment]
你好，麻烦现在再尝试下。

**Comment by DavyLin** [comment]
@sdjcw 我刚才试了生产环境，是可以的，我现在再试下预备环境，生产环境访问时，会使用https，但引用的js 却是http地址，提示不安全，这个需要怎么改造，文档地址在？

**Comment by sdjcw** [comment]
请问你的 js 文件是保存在项目代码里，还是 cdn ？

**Comment by DavyLin** [comment]
@sdjcw 预备环境也可以正常部署了，先谢谢：）js 保存在项目代码里面的，

**Comment by sdjcw** [comment]
那应该改下前段页面，加载 js 时使用 https 的地址。

**Comment by DavyLin** [comment]
`<%
    String path = request.getContextPath();
    String basePath = request.getScheme() + "://"
            + request.getServerName() + ":" + request.getServerPort()
            + path + "/";
//			 String srcUrl = request.getParameter("service");
//			 srcUrl = URLEncoder.encode(srcUrl);
%>`

引用路径
`<script type="text/javascript" src="<%=basePath%>js/login.js"></script>`


request.getScheme()获取 到的为什么是http，而不是https呢。。是不是服务端这块，需要做什么设置

**Comment by sdjcw** [comment]
因为云引擎服务器是在反向代理服务器后面，反向代理服务器会把 https 卸掉，然后添加 `X-Forwarded-Proto: https` 的 header，在内网都是 http 传递，所以建议检查 `X-Forwarded-Proto` 的值。

**Comment by leeyeh** [comment]
前端使用 `src="//xxxx/js/login.js"` 就好了，不需要去指定 scheme。

**Comment by DavyLin** [comment]
@sdjcw @leeyeh 好的，谢谢：）我调整下代码试试！
