### ISSUE TITLE
命令行部署时自动为版本添加可读的备注

### ISSUE THREAD

**Issue by jysperm** [leancloud/lean-cli#110]
之前所有从命令行部署的版本的备注都是「从命令行工具构建」，很难区分，构建相关的接口都是有一个 `comment` 参数的，可以设置自定义的备注，可以展示在网页控制台上。

我的建议是这样，如果当前目录是一个 Git 仓库的话，用当前的 Commit Message 作为备注。如果 Git 工作区是干净的（从上一个 Commit 以来没有修改过）就直接用 Commit Message，例如「Add some file」，如果已经改过文件就加个 WIP 的前缀：「WIP: Add some file」。

**Comment by aisk** [comment]
- [x] 增加备注选项
- [ ] 自动增加备注
