### ISSUE TITLE
.leanignore 文件在 windows 系统下不能正确工作

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#120]
https://forum.leancloud.cn/t/npm-leanengine/11488/9

**Comment by wuyingfengsui** [comment]
@aisk 这个问题修复了吗

**Comment by aisk** [comment]
不好意思，我在 win10 下没有复现出来，最近准备切换到 win7 试一下。能否提供一下您遇到问题的环境吗？

**Comment by wuyingfengsui** [comment]
win 10 x64
lean version 0.5.2

**Comment by aisk** [comment]
感谢，另外是在 cmd.exe 还是 powershell 或者 cygwin 下遇到的问题？

**Comment by wuyingfengsui** [comment]
cygwin，我用的是git自带的那个命令行
