### ISSUE TITLE
LeanCache 移除对 Redis 的依赖

### ISSUE THREAD

**Issue by sdjcw** [leancloud/lean-cli#128]
希望使用 LeanCache 管理内部 Redis 集群，如果产品本身还依赖 Redis 很容易造成循环依赖。

**Comment by aisk** [comment]
不是很明白，好像一直都没有依赖 redis？

**Comment by sdjcw** [comment]
有的，主要是一些锁使用 redis 实现，还有一些全局开关。

**Comment by aisk** [comment]
好像提错 repo 了……

**Comment by sdjcw** [comment]
Orz
