### ISSUE TITLE
支持 env / unset 子命令

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#131]
用来设置线上环境变量：

列出环境变量：
```
$ lean env
FOO=foo
BAR=bar
```

修改／添加环境变量：
```
$ lean env export BAZ=baz
```

删除环境变量：

```
$ lean unset FOO
```

另外支持 --prod 参数指定生产环节／预备环境。

**Comment by leeyeh** [comment]
lean env [list|set|unset] ?

**Comment by aisk** [comment]
想要支持类似 shell 的格式，不过可能确实容易有歧意，那就使用 👍 来给上面两种 API 投票吧。

@leeyeh @jysperm @sdjcw
