### ISSUE TITLE
lean init 选择美国节点提示用户未登录

### ISSUE THREAD

**Issue by nervouna** [leancloud/lean-cli#154]
<img width="212" alt="screen shot 2016-11-17 at 23 07 59" src="https://cloud.githubusercontent.com/assets/1436139/20394513/bd7d4c5a-ad1a-11e6-85aa-4fba7a1d8526.png">

**Comment by aisk** [comment]
改成在执行 `init` / `switch` 命令时，只显示已经登录过的节点了。如果只登录过一个节点，就跳过选择节点的步骤。
