### ISSUE TITLE
增加 lean checkout app-name 的功能

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#176]
目前支持 lean checkout app-id ，但是不是很直观。希望增加 `lean checkout app-name --region=US` 的功能，方便一些用户快捷切换应用／在自动化脚本里切换应用。

**Comment by godblesshugh** [comment]
可能还需要原来的那个 lean app add app-name app-key 的方式，才好将多个应用一起关联进来。

**Comment by aisk** [comment]
@godblesshugh 目前不需要了，现在命令行工具是需要登录的，登录之后调用 `lean checkout app-name` 之后可以直接用当前登录用户的权限去获取 app-id 。

**Comment by godblesshugh** [comment]
了解
