### ISSUE TITLE
lean up 支持 --cmd=xxx 参数

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#177]
允许用户自定义启动命令，方便类似需要使用 `python -m pdb wsgi.py` 以及 `npm server.js --debug` 的用户。

**Comment by leeyeh** [comment]
`lean up -- --debug`

**Comment by aisk** [comment]
像 Python 这种形式（python -m pdb wsgi.py），没办法把参数传递到命令中间，就不太好实现了。

**Comment by aisk** [comment]
后来讨论，`lean up -- --debug` 和 `lean up --cmd=xxxx` 都需要实现。
