### ISSUE TITLE
Malformed http status code 'HTML'

### ISSUE THREAD

**Issue by xixilive** [leancloud/lean-cli#179]
执行`lean deploy`命令时Go报如下错误, 何解? go v1.5 and v1.7都是

```
获取应用信息
 ✗ Get https://app-router.leancloud.cn/1/route?appId=XXXXXX
: malformed HTTP status code "HTML"
```

**Comment by aisk** [comment]
「XXXXXX」是这么显示的还是粘贴过来的时候修改的？

如果就是这么显示的话，应该是关联应用出错了，重新在项目目录下执行 `lean checkout` （不加参数），根据选项操作就可以了。

如果这里本来是正确的话，麻烦重试一下，或者直接用浏览器打开这个页面，看下能不能正确访问。

**Comment by xixilive** [comment]
那个XXX是我的AppID呀,
```
curl https://app-router.leancloud.cn/1/route?appId=XXX

# response OK
{"ttl":3600,"push_router_server":"router-g0-push.leancloud.cn","api_server":"api.leancloud.cn"}

# Go http OK
http.Get("https://app-router.leancloud.cn/1/route?appId=XXXX")
```

**Comment by aisk** [comment]
重试过了还是不行？

**Comment by xixilive** [comment]
谢谢, 是的

**Comment by xixilive** [comment]
``` shell
lean --version
> lean version 0.5.4
```

**Comment by xixilive** [comment]
https://github.com/golang/go/issues/5522

**Comment by aisk** [comment]
麻烦检查是不是设置了代理，目前命令行工具发送 HTTP 请求是会走代理的。（比如环境变量设置了 HTTPS_PROXY ）

**Comment by xixilive** [comment]
还是一样的~~ 呜呜~~, 貌似是Go里面raise的error, 我对Go不了解, 有local go / global go的说法吗?

**Comment by xixilive** [comment]
```
curl -I https://app-router.leancloud.cn/1/route?appId=q1PDu4ALU7u0eiGUXeH0dCBB-gzGzoHsz

HTTP/1.1 200 OK
Server: Tengine
Date: Tue, 13 Dec 2016 06:56:35 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 95
Connection: keep-alive
cache-control: public,max-age=3600
x-request-id: 8vgurui720glqqqonnrg8pjnr8oe2v0r
access-control-allow-origin: *
access-control-expose-headers: 
access-control-allow-credentials: true
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
```

和你们server的这个header有关系吗? 
```
Access-Control-Expose-Headers: 空
```

**Comment by aisk** [comment]
应该没关系，命令行工具不认这些 header 的。

**Comment by xixilive** [comment]
为什么在readResponse时读出了 "HTML" 这个字符串呢?

https://github.com/golang/go/blob/master/src/net/http/response.go#L164
https://github.com/golang/go/blob/master/src/net/http/response.go#L168

**Comment by aisk** [comment]
Hi @xixilive ，不知道你那里有没有安装 go 的编译环境，如果有的话，可以尝试 clone 这个 repo 的代码，自己编译一下，在 https://github.com/leancloud/lean-cli/blob/master/lean/api/app_router.go#L26 这个地方打个断点，或者直接 `fmt.Println(resp)`，看一下输出是啥。
