### ISSUE TITLE
window环境下运行lean up出现乱码

### ISSUE THREAD

**Issue by tooyond** [leancloud/lean-cli#189]
![image](https://cloud.githubusercontent.com/assets/93812/21284068/61342714-c44b-11e6-8b4b-d0e3d21807d7.png)

> λ lean up
>  正在检测运行时
>  检测到 node.js 运行时
>  云函数调试服务已启动，请 >� ���硔���曵���跧���吙���芮���鼗���ﯼ���h�t�t�p�:/�/�l�o�c�a�l�h�o�s�t�:�3�0�0�1�
> ：http://localhost:3000

虽然不影响使用,但用起来总是很不爽的

环境是win8 在cmder下运行 
版本是 lean-windows-amd64.exe v0.5.4

**Comment by tooyond** [comment]
λ lean up
 > 正在检测运行时
 > 检测到 node.js 运行时
 > 云函数调试服务已启动，请 >� ���硔���曵���跧���吙���芮���鼗���ﯼ���h�t�t�p�:/�/�l�o�c�a�l�h�o�s�t�:�3�0�0�1�
：http://localhost:3000

**Comment by aisk** [comment]
收到，尽快修复。

**Comment by liubiqu** [comment]
我这边偶尔也会出现如下：

使用开发工具idea 的terminal

> 获取应用信息
 > 获取云引擎信息
 > 云函数调试服务已启动，请使用浏览器访问：http://localhos t>: 3�0�0�1目
已启动，请使用浏览器访问：http://localhost:3000
