### ISSUE TITLE
lean-cli 部署找不到文件目录 leanengine.zip: no such file or directory

### ISSUE THREAD

**Issue by CaosBad** [leancloud/lean-cli#190]
在更新过新版的 lean-cli 之后，运行 lean deploy 后 log 出现如下错误:
```
✓ 获取应用信息
 ✓ 准备部署至目标应用：deepValleyServer (xxx)
 ✓ 获取应用分组信息
 ✓ 准备部署应用到生产环境: web
 ✓ 正在检测运行时
 ✓ 检测到 Python 运行时
 ✓ 找到运行文件 `/Users/xxx/virtualenvs/flask/bin/python2.7`
 ✗ open /var/folders/fm/wp14w91x5832kxjkwtdzr5f40000gn/T/leanengine636923386/leanengine.zip: no such file or directory

```

 - 操作系统： macos
 - 版本: 10.12.1
 - 安装环境工具为 brew
  - lean version 0.5.4
哪位知道是什么问题？

**Comment by aisk** [comment]
是从之前 npm 版本的工具更新到目前这个版本之后遇到的问题，还是从 0.5.4 之前版本更新到这个版本之后，才遇到的问题？

另外不知道是否方便把项目源码发送过来看一下吗？如果方便的话，可以把代码发到我邮箱 lan@leancloud.rocks 。

**Comment by CaosBad** [comment]
已经解决了，之前使用 npm 版本配置的  .leanignore 文件突然好用了。。导致项目源码没能被识别~我去掉错误的配置就可以了~  
多谢您的回复~

**Comment by aisk** [comment]
Hi，能否告知一下之前的 .leanignore 文件内容是什么吗，我看一下代码层面能不能避免这种情况。

**Comment by CaosBad** [comment]
之前的源码是忽略了 前端源文件目录的配置：
`/FE/*.*`
因为一直没有效果，部署的过程中 lean 会把 node_modules 一起压缩
后来我把前端文件夹拷出了项目文件夹
