### ISSUE TITLE
允许单独启用云函数调试服务

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#194]

**Comment by aisk** [comment]
@sdjcw 好像不太好实现，如果不启动用户代码的画，很难获得云函数元信息。

**Comment by sdjcw** [comment]
命令行工具启动时需要用户通过参数指定 host 和 port，命令行工具去获取需要的信息，这样即使是远端的云引擎应用貌似也行。

Long Ang <notifications@github.com>于2017年1月2日周一 下午1:48写道：

**Comment by aisk** [comment]
ok
