### ISSUE TITLE
检查重复／非法的云函数名

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#199]
目前遇到类似 

```js
AV.Cloud.define('', () => {});
```

的云函数，会导致进程崩溃。另外如果有重复的云函数，只会展示其中的一个，这样对于调试会带来各种问题，最好给出提示。

- [x] Don't crash
- [ ] Warning user

**Comment by jysperm** [comment]
准备在 Node SDK 2.0 里做这个事情
