### ISSUE TITLE
cli 架构

### ISSUE THREAD

**Issue by sunng87** [leancloud/lean-cli#2]
一个主命令 `lean` 负责调度

lean 会查找当前目录和 path 下面所有的 lean-xxxx 的可执行文件。每一个 subcommand 都是一个可执行文件，内置的 subcommand 的可执行文件会和 lean 一起发布。第三方也可以在 lean-cli-lib 的基础上编写插件，以 lean-xxxx 的格式命名，安装到 path 里，或者 .lean/thirdparty 一类的目录下。

lean-cli-lib 包含一组共用的基础，比如读取认证信息，读取项目详细之类的。这个lib可以发布到包管理器上去。

lean 启动后根据 subcommand 找到对应 的 lean-xxxx ，并把所有命令行参数传给 lean-xxx 来执行。

lean 支持一些 global options，除了自己的 -v -h 以外，其余的可以作为环境变量传给 lean-xxx 的子命令。

当 lean 没有参数执行的时候，可以列出所有可用的 subcommand 并带有一个简单的说明，这个说明可能是 lean-xxxx -h 的第一行

**Comment by aisk** [comment]
我觉得 lean 这个命令就可以解析认证信息与读取项目内容，然后把这些数据保存在当前进程的环境变量中，自进程再从其中读取。

**Comment by sunng87** [comment]
也可以，如果没有什么共用的东西的话就可以把这个库去掉了，那样更轻松
所有的上下文信息都从环境变量里传递

**Comment by aisk** [comment]
目前的实现是大部分 subcommand 都是直接在主命令里实现的（考虑到每个 subcommand 都单独出来的话有些不必要的复杂度）。

收到没有在主命令下实现的 subcomand，会在 `$PATH` 下找 `lean-$subcommand`，找到的话把参数传过去执行，没有找到的话直接报错。
