### ISSUE TITLE
云引擎读取中文文件时获取文件名乱码

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#207]
关联工单：3574

```js
var studentFolder = require("path").join(__dirname, './cloudFuncs/score')
var fs = require('fs')

fs.readdir(studentFolder, (err, files) => {
  files.forEach(function(file) {
    if (file.indexOf('.json') !== -1) {
      console.log('school name: ', file)
    }
  })
})
```

如果score中的文件名为中文：测试.json，console.log()出为乱码

**Comment by aisk** [comment]
- http://stackoverflow.com/questions/30026083/creating-a-zip-archive-with-unicode-filenames-using-gos-archive-zip
- https://my.oschina.net/chai2010/blog/186211

看来 go 自带的 zip 模块默认只支持 ascii 字符的文件名，如果需要使用 utf-8 的话需要修改文件 Header。目前使用的 archivex 模块并不支持修改 Header，看来要干掉这个模块直接使用 zip 模块才能修掉这个 bug。

Windows 环境需要额外测试。

**Comment by jysperm** [comment]
看起来 archivex 已经被换掉了
