### ISSUE TITLE
CN / US 节点采用浏览器的方式登录

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#214]
有一部分用户使用的 GitHub / QQ 等第三方账号登录 LeanCloud 平台，并且没有设置密码。对于这部分用户，只能通过「找回密码」功能来重新设置一个密码才能进行登录。如果考虑用户体验的话，应该在 CN ／ US 节点，都采用现在 TAB 节点的通过浏览器的方式进行登录。

**Comment by dlmyb** [comment]
现在 LeanCloud 已经默认第三方账户注册后要输入密码了。。
这个恐怕只用在输入密码时候，提示一下就好吧？

**Comment by aisk** [comment]
嗯，似乎现在没有这个问题了 👌
