### ISSUE TITLE
Typo or bug?

### ISSUE THREAD

**Issue by nervouna** [leancloud/lean-cli#217]
<img width="435" alt="screen shot 2017-01-14 at 15 15 23" src="https://cloud.githubusercontent.com/assets/1436139/21953286/bfa73d4e-da6d-11e6-8dfb-b54246627689.png">

**Comment by aisk** [comment]
其实我比较介意最后那个 404 是啥情况

**Comment by nervouna** [comment]
<img width="543" alt="screen shot 2017-01-16 at 12 32 33" src="https://cloud.githubusercontent.com/assets/1436139/21971046/e5ecb26a-dbe7-11e6-9e2f-c76ba0bb606c.png">

**Comment by nervouna** [comment]
这个 404 是无法根据本地存储的 app ID 在账户里找到对应的应用

**Comment by aisk** [comment]
就是说这个 app 确实已经删除了／当前应用没权限访问对吧？那看来不用管了 💁‍♂️

**Comment by nervouna** [comment]
💁🏻‍♂️
