### ISSUE TITLE
VS code内置终端无法使用lean命令

### ISSUE THREAD

**Issue by BetaMee** [leancloud/lean-cli#218]
Windows环境下已经装了最新版的lean-cil，但无法在vscode内置终端使用，CMD中却可以使用。
[vscode贴图](https://1drv.ms/i/s!Aj3YSOj5n5j2kmNWVYw6RzrejoGA)
[CMD贴图](https://1drv.ms/i/s!Aj3YSOj5n5j2kmTpY6-WP9Id-N8K)

**Comment by aisk** [comment]
请问是直接使用 .msi 安装包进行安装的吗？如果是的话，看来 vscode 下的内置终端的 PATH 变量与 cmd.exe 的并不相同.

目前可以通过使用绝对路径来绕过这个问题，命令行工具的默认安装路径是 `C://Windows/system` 或者 `C://Windows/system64`

**Comment by BetaMee** [comment]
是用.msi安装包的，但我看vscode 内置终端引用的路径是`"C:\\WINDOWS\\system32\\cmd.exe"`，之前使用旧版lean-cil也没问题

**Comment by aisk** [comment]
都是 cmd.exe ，但是对 PATH 的处理不同吧。旧版的命令行工具，是 node 安装过程中，帮你修改系统的 PATH 环境变量的。

**Comment by BetaMee** [comment]
暂时只能开外置终端使用了，期待之后有更好的解决方法 。

**Comment by aisk** [comment]
可以调研一下 vs code 设置 PATH 的相关功能。

**Comment by BetaMee** [comment]
VS code最新版内置终端换为了powershell.exe，然后能使用了lean-cil了
