### ISSUE TITLE
使用lean deploy去部署美国节点错误（使用demo中的 java-war-getting-started）

### ISSUE THREAD

**Issue by yao201212** [leancloud/lean-cli#230]
使用lean deploy命令 部署java工程（demo中的 java-war-getting-started 没有做任何修改）
日志如下：
 ✓ 获取应用信息
 ✓ 准备部署至目标应用：GSpot-dev (fIulGDH04bLH9VdyczNF4C0Q-MdYXbMMI)
 ✓ 获取应用分组信息
 ✓ 准备部署应用到生产环境: web
 ✓ 正在检测运行时
 ✓ 检测到 Java 运行时
 ✓ > 没有找到 .leanignore 文件，根据项目文件创建默认的 .leanignore 文件
 ✓ 压缩项目文件
 ✓ 上传应用文件 17.03 KB / 17.03 KB [===============================] 100.00% 4s
 ✓ 开始构建 20170213-031622
 ✓ 正在下载应用代码 ...
 ✓ 正在解压缩应用代码 ...
 ✓ 运行环境: java-war (leanengine/java-war-base-8)
 ✓    删除临时文件 赖项 ...
 ✗ Get https://us.leancloud.cn/1.1/engine/events/poll/1486955782612?from=2017-02-13T03:16:23.602Z: net/http: TLS handshake timeout

 记得去年能正常部署这个，现在不可以了，帮忙查看下是什么问题

**Comment by aisk** [comment]
应该是网络问题导致的。可以在控制台的日志里观察一下这次日志是否部署成功了。
