### ISSUE TITLE
本地测试云函数的界面优化建议

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#236]
关联工单：3954

目前云函数名称下拉选择，而且没有规律，查找起来非常不方便，目前大部分应用的接口都超过50个，例如：xxxxxxxxxxx-gzGzoHsz

建议改为输入并可以自动提示，或者做一个下拉长框加定位也行，总之就是要比现在方便一些。

因为这个功能开发的使用频率非常高，建议优化一下，谢谢。

**Comment by nervouna** [comment]
其实下拉框也可以直接敲键盘定位的，如果用的是浏览器的原生控件

**Comment by liubiqu** [comment]
我也知道，但毕竟还是不太好用。

**Comment by liubiqu** [comment]
0.7.1版本已经优化了，感觉非常好
