### ISSUE TITLE
提供 Mac 版安装包

### ISSUE THREAD

**Issue by nervouna** [leancloud/lean-cli#262]
https://forum.leancloud.cn/t/golang-lean-cli-go-gobootstrap/14017

貌似在装 Go lang 的时候会撞墙，现在好像没有好的方法绕过去？

**Comment by aisk** [comment]
理论上讲不会撞墙，并且国内有镜像。

**Comment by nervouna** [comment]
论坛里那位好像是链接 googleapis.com 的时候撞墙了，很神奇。

**Comment by aisk** [comment]
理论上 lean-cli 和 go 都是会被 homebrew 预编译，安装的时候直接下载预编译的二进制文件的，目前 host 在 [bintray](https://bintray.com/homebrew) 上，目前国内访问没有撞墙。

当然根据论坛的描述，他应该是 homebrew 设置有问题（比如安装了 .pkg 格式的安装包，搞乱了 `/usr/local` 目录权限）。
