### ISSUE TITLE
lean deploy 出现 panic: read env/include/python2.7: is a directory

### ISSUE THREAD

**Issue by wecodexyz** [leancloud/lean-cli#267]
✓ 准备部署应用到生产环境: web
 ✓ 正在检测运行时
 ✓ 检测到 Python 运行时
 ✓ 找到运行文件 `/Users/lancelot/PycharmProjects/wecode/env/bin/python2.7`
 ⠼ panic: read env/include/python2.7: is a directory, 错误 ID: 2d5bb69bfa3a40db92c01cba7cf05344

**Comment by aisk** [comment]
这个问题看上去比较奇怪。另外可以尝试升级一下 cli 的版本（`$ brew upgrade lean-cli`），对这部分代码做了调整。

**Comment by wecodexyz** [comment]
已解决问题，thx
