### ISSUE TITLE
在 Windows 下将 lean env 输出结果中的 export 改为 set

### ISSUE THREAD

**Issue by nervouna** [leancloud/lean-cli#272]
要不没法直接用了……

**Comment by aisk** [comment]
没找到比较靠谱的方法，判断当前环境是 DOS 环境。如果单纯的判断是 windows 的话，用户有可能在 cygwin /mingw 等环境下使用，导致误判。目前的方案是增加了 `--template` 参数，用户自己指定输出模版。

**Comment by aisk** [comment]
增加了个不精确的方法来检测是否是 DOS 环境。
