### ISSUE TITLE
支持二次认证

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#343]
https://github.com/leancloud/avfr/issues/1233

**Comment by dlmyb** [comment]
。。。这个链接是社区里的吗？

**Comment by aisk** [comment]
这个暂时链接到私有仓库的文档上了……

**Comment by dlmyb** [comment]
话说，LeanCloud 有打算包装 Go SDK 和 Go 云引擎的计划吗？

**Comment by aisk** [comment]
还没有看到有用户提到有使用 Go 的需求，所以暂时还没有计划😂
