### ISSUE TITLE
云引擎 php部署失败，需要更新apt-get 

### ISSUE THREAD

**Issue by jianoll** [leancloud/lean-cli#379]
F:\  lean deploy
[INFO] 当前命令行工具版本： 0.16.2
[REMOTE] 开始构建 20171017-151218
[REMOTE] 正在下载应用代码 ...

Get:38 http://security.ubuntu.com/ubuntu xenial-security/main amd64 nginx all 1.10.3-0ubuntu0.16.04.2 [3490 B]
Fetched 18.4 MB in 3s (5472 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/libg/libgd2/libgd3_2.1.1-4ubuntu0.16.04.7_amd64.deb  404  Not Found [IP: 91.189.88.152 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[INFO] 删除临时文件
部署失败

**Comment by jysperm** [comment]
已修复，麻烦重试一下。

另外这类问题建议在工单或用户论坛提问 https://forum.leancloud.cn

**Comment by jianoll** [comment]
ok
