### ISSUE TITLE
支持区分华东节点和华北节点

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/lean-cli#387]
目前 `lean switch` 只显示「国内」和「美国」，无法选择部署华东节点的云引擎代码。

**Comment by jysperm** [comment]
应该是要登录过 TAB 的帐号才会显示 TAB，`lean login --region TAB`

**Comment by BinaryHB** [comment]
https://github.com/leancloud/lean-cli/issues/387#issuecomment-347786121

SDK 节点的命名，需要更改和统一。TAB 再无法表示华东节点。

**Comment by BinaryHB** [comment]
节点命名的更改在其他 issue 跟踪，先关了。
