### ISSUE TITLE
支持 Python virtualenv 相关功能

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#39]
希望能集成 Python 的 virtualenv：
- init 之后就在当前目录下创建一个 virtualenv 的目录，在此文件夹下创建一个 virtualenv 环境（如果机器上安装了 virtualenv 的话）。
- up 时检测当前目录下是否有 virtualenv 目录，有的话自动使用此 virtualenv 启动项目。
- 增加子命令 pip-install，在 virtualenv 下安装 requirements.txt 中的依赖。

**Comment by jysperm** [comment]
我觉得还是不要做这么多特定语言的支持了吧，我感觉可以只在 up 的时候检查一下 virtualenv，创建 virtualenv 和安装依赖让用户自己来做。

**Comment by aisk** [comment]
@jysperm 也可以，那就先坐简单的吧，以后有需求再说。
