### ISSUE TITLE
lean-cli 0.18.0 登录 bug

### ISSUE THREAD

**Issue by syang2forever** [leancloud/lean-cli#390]
lean-cli 0.18.0 在登录后仍会提示未登录，但在0.17.1中正常，推测内部修改时出现问题

下图中的 **lean** 是 0.18.0 版本，而 **lean-linux-x64** 是 0.17.1 版本
![bug](https://user-images.githubusercontent.com/25731241/36828026-279350dc-1d52-11e8-8096-c97154552205.png)

**Comment by jysperm** [comment]
已在 https://github.com/leancloud/lean-cli/pull/389 中修复，今天或明天会发布

**Comment by jysperm** [comment]
0.18.1 已发布
