### ISSUE TITLE
lean init 创建 Java 应用模板有误

### ISSUE THREAD

**Issue by sdjcw** [leancloud/lean-cli#395]
创建 Java 应用时，提示只有一个 Spring Boot 应用模板：

```
[?] 请选择需要创建的应用模版
 1) Spring Boot
```

但创建完成之后却是一个 Java WAR 项目。

需要改得地方有两个：

* 应用模板有两个：Java WAR 和 Spring Boot。
* Spring Boot 模板能正确创建。

**Comment by Mirakyux** [comment]
还没有解决吗

**Comment by weakish** [comment]
blocked by #442

**Comment by sdjcw** [comment]
Link https://github.com/leancloud/pack-scaffold/pull/1

**Comment by jysperm** [comment]
看起来已经改好了
