### ISSUE TITLE
lean-cli 登录时选择中国/国际，选择 app 时不再能切换。

### ISSUE THREAD

**Issue by hjiang** [leancloud/lean-cli#401]

**Comment by jysperm** [comment]
有很多用户是同时用两个节点的（比如遇到很多用户生产环境在美国节点，但用国内节点来调试）。

目前 lean-cli 的逻辑是登录了多个节点（比如 `lean login` 之后又 `lean login --region US`）才会在 `lean switch` 的时候出现节点选择，如果只登录一个节点是不会有节点选择的，感觉这个逻辑没有大问题。

**Comment by hjiang** [comment]
其实我的意思是说应该要能选择。比如一个用户 lean login 了中国节点，然后再选 app 的时候就直接显示中国节点的 app 了。要怎样才能选美国节点的 app 不太明显。最好 switch 之类的命令也能支持 region，或者提示用户选择。

**Comment by jysperm** [comment]
那就在 lean login 的时候加一个交互式的节点选择，代替目前的命令行参数

**Comment by jysperm** [comment]
https://github.com/leancloud/lean-cli/pull/407
