### ISSUE TITLE
brew install lean-cli时，download go--gotools 443 timed out

### ISSUE THREAD

**Issue by NickBang** [leancloud/lean-cli#416]
$ brew install lean-cli
Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version.

==> Installing dependencies for lean-cli: go
==> Installing lean-cli dependency: go
==> Downloading https://dl.google.com/go/go1.12.src.tar.gz
Already downloaded: /Users/zl/Library/Caches/Homebrew/downloads/0f64991f71d1a7e34370af429189d0a6757948abf4f26cd18f4bd450f59b34dc--go1.12.src.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.7.darwin-amd64.tar.gz
Already downloaded: /Users/zl/Library/Caches/Homebrew/downloads/ad0901a23a51bac69b65f20bbc8e3fe998bc87a3be91d0859ef27bd1fe537709--go1.7.darwin-amd64.tar.gz
==> ./make.bash --no-clean
==> /usr/local/Cellar/go/1.12/bin/go install -race std
==> Cloning https://go.googlesource.com/tools.git
Cloning into '/Users/zl/Library/Caches/Homebrew/go--gotools--git'...
fatal: unable to access 'https://go.googlesource.com/tools.git/': Failed to connect to go.googlesource.com port 443: Operation timed out
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "go--gotools"
Failure while executing; `git clone --branch release-branch.go1.12 https://go.googlesource.com/tools.git /Users/zl/Library/Caches/Homebrew/go--gotools--git` exited with 128. Here's the output:
Cloning into '/Users/zl/Library/Caches/Homebrew/go--gotools--git'...
fatal: unable to access 'https://go.googlesource.com/tools.git/': Failed to connect to go.googlesource.com port 443: Operation timed out

查找国内镜像尝试之后还是失败。
Thanks

**Comment by jysperm** [comment]
brew 已经不支持 10.11 了，所以会 fallback 到从源码编译，看起来是你的电脑无法连接到 
go.googlesource.com。

这样的话推荐你直接从 http://releases.leanapp.cn/#/leancloud/lean-cli/releases 下载可执行文件。

**Comment by NickBang** [comment]
安装好了、非常感谢！
