### ISSUE TITLE
windows lean login 后，lean info/init 提示未登陆

### ISSUE THREAD

**Issue by zhoui** [leancloud/lean-cli#417]
C:\Users\lx>lean login -u xxxxxx@qq.com -p xxxxxx
[?] Please select a region:
 1) China North
 2) United States
 3) China East
 => 3
[INFO] Login succeeded:
[INFO] Username: xxxxxx
[INFO] Email: xxxxxx@qq.com

C:\Users\lx>lean info
**[ERROR] Please login first**

C:\Users\lx>lean init
**Please login first.**

**Comment by jysperm** [comment]
如果你在 China East 没有应用的话，麻烦先在控制台上创建一个应用

**Comment by zhoui** [comment]
切换region后问题解决。感谢
