### ISSUE TITLE
nodejs 脚手架项目的下载地址需要修改

### ISSUE THREAD

**Issue by jwfing** [leancloud/lean-cli#420]
https://cdn1.lncld.net/cloud-code-scaffold/node-js-getting-started-f67b77639d1132e02ca64fb2358aa2f7fe3e774b.zip

**Comment by weakish** [comment]
repo 应该是这个 https://github.com/leancloud/pack-scaffold

应用应该是这个 rua93xos8olfyrxmow5y3hekt4fqupjlitbeavlicxf40it8 （你名下的「LeanCloud内部 - 云代码框架包更新」）

**Comment by weakish** [comment]
看起来似乎是把 「LeanCloud内部 - 云代码框架包更新」的 `URL` 的表所有记录的 `url` 字段全部替换一下就可以。

**Comment by jysperm** [comment]
顺便提一下，关于这个脚手架，远期的计划是把 pack-scaffold 的功能合并到 releases.leanapp.cn

**Comment by jysperm** [comment]
已手工修改 pack-scaffold 中的记录
