### ISSUE TITLE
Java 环境本地调试不依赖 getEngineConfig

### ISSUE THREAD

**Issue by weakish** [leancloud/lean-cli#423]
getEngineConfig 所用的 `leanengine.yaml` 仅供线上使用。

去掉这个依赖前需要增加一个机制让用户指定 `lean up` 需要的相关命令。

**Comment by jysperm** [comment]
已实现在 https://github.com/leancloud/lean-cli/pull/502

**Comment by jysperm** [comment]
1.0.0 已发布
