### ISSUE TITLE
Could not detect Language

### ISSUE THREAD

**Issue by ash0080** [leancloud/lean-cli#426]
lean-cli  0.20.1

虽然不影响部署
但是运行任何命令都会显示

```
[INFO] Retrieving app info ...
[ERROR] Could not detect Language
[ERROR] Could not detect Language
[ERROR] Could not detect Language
[INFO] Deploying 
```

**Comment by weakish** [comment]
项目是什么语言环境？

**Comment by ash0080** [comment]
Node.js

**Comment by weakish** [comment]
试下昨天发布的 0.21.0 ？

**Comment by ash0080** [comment]
![屏幕快照 2019-07-31 10 39 49](https://user-images.githubusercontent.com/2803210/62179643-d2c73580-b37f-11e9-86c0-f48d8f42382f.png)

**Comment by weakish** [comment]
这个报错应该是开发机器系统的 locale 设置有问题

**Comment by ash0080** [comment]
那要怎么设置？ 这台开发机一直没出现过这个问题 直到上次升了 0.20

**Comment by ash0080** [comment]
OK 我尝试 从 lean init 新创建一个项目 问题依旧

**Comment by ash0080** [comment]
我觉得这版 bug 超多
lean info 
还会提示未登录 但是又能正常拿到用户信息和项目绑定信息

**Comment by weakish** [comment]
> 我的理解 lean 应该是抓本地 package.json 至少官方文档里是这么写的

没错，是通过检测 package.json 来判断 node runtime 的。

但是这里的 Could not detect Language 其实是 lean cli 依赖的模块的报错信息，这里的 Language 指的不是编程语言，而是自然语言。所以之前回复说是开发机器系统的 locale 设置问题。

之前没看到过，可能是因为您升级了系统或者终端模拟器。您可以尝试在系统设置和终端模拟器设置里配置下语言、编码等选项，或者在 shell 的 profile 文件里设置环境变量 `LC_ALL` 或 `LANG`。

后续我们会在文档中加一个 faq，感谢反馈。

> lean info
> 永远提示未登录 但是又能正常拿到用户信息和项目绑定信息

提示未登录，可能是您通过 `lean login` 在华北节点登录了，所以能够「正常拿到」华北节点的「用户信息和项目绑定信息」，但是会报错华东节点、LeanCloud 国际版未登录，一般情况下您可以直接忽略这样的报错。

后续我们会改进这方面的用户体验（ #429  ），再次感谢反馈。

**Comment by ash0080** [comment]
好的  了解了 谢谢
