### ISSUE TITLE
更友善的多节点登录体验

### ISSUE THREAD

**Issue by weakish** [leancloud/lean-cli#429]
比如，`lean login` 只在华北节点登录，`lean info` 会报错华东节点、国际版未登录：

```
[ERROR] Failed to retrieve user info from region: us: LeanCloud API error 1: User doesn't sign in.
[ERROR] Failed to retrieve user info from region: tab: LeanCloud API error 1: User doesn't sign in.
```

需要再 `lean login` 两次，分别选择华东节点、国际版：

1. `lean login` 三次而不是一次性完成比较麻烦
2. 不容易想到要再次 `lean login`
3. 有的用户只关心一个节点，显示其他节点的登录报错徒增疑惑

**Comment by jysperm** [comment]
只有曾经登录过其他节点才有这个提示，没登录过是没有的，不过提示确实有待改进

**Comment by jysperm** [comment]
现在想起来好像没啥需要改进的？先关掉了
