### ISSUE TITLE
0.21.0版本lean up一直提示关于goroutine的错误

### ISSUE THREAD

**Issue by papabattery** [leancloud/lean-cli#433]
我用的是最新版本0.21.0，在lean up的时候服务跑起来了，但是在访问的时候一直报的是关于goroutine的错误
`http: panic serving 127.0.0.1:49863: Options http://localhost:3000/1.1/functions/_ops/metadatas: dial tcp [::1]:3000: connect: connection refused
goroutine 27 [running]:
net/http.(*conn).serve.func1(0xc000519cc0)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1767 +0x139
panic(0x15439e0, 0xc000230270)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
github.com/leancloud/lean-cli/console.(*Server).appInfoHandler(0xc0003ea0e0, 0x16d93e0, 0xc000386d20, 0xc000120600)
        /private/tmp/lean-cli-20191018-81724-1iwv9ly/lean-cli-0.21.0/src/github.com/leancloud/lean-cli/console/server.go:84 +0x7a5
net/http.HandlerFunc.ServeHTTP(0xc0005421d0, 0x16d93e0, 0xc000386d20, 0xc000120600)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2007 +0x44
github.com/leancloud/lean-cli/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00054e0f0, 0x16d93e0, 0xc000386d20, 0xc000120600)
        /private/tmp/lean-cli-20191018-81724-1iwv9ly/lean-cli-0.21.0/src/github.com/leancloud/lean-cli/vendor/github.com/gorilla/mux/mux.go:114 +0xdb
net/http.serverHandler.ServeHTTP(0xc00054a460, 0x16d93e0, 0xc000386d20, 0xc000120400)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000519cc0, 0x16dae60, 0xc0000ec500)
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.13.1/libexec/src/net/http/server.go:2927 +0x38e
`

**Comment by papabattery** [comment]
另外还有一个问题，就是论坛https://forum.leancloud.cn/ 我的账号一直登陆不了，输入账号密码就有一个弹框一闪而过，始终登陆不了，没办法在论坛提问和回复问题

**Comment by weakish** [comment]
论坛是通过 leancloud 账号 oauth 登录的。您可以尝试换个浏览器试试。如果仍有问题可以写信给 support at leancloud.rocks 咨询。

https://forum.leancloud.cn/t/mac-lean-lean-up-3001-goroute/22157 <-- 这个帖子是您用其他账号发的吗？

**Comment by papabattery** [comment]
是的。https://forum.leancloud.cn/t/mac-lean-lean-up-3001-goroute/22157 <-- 这个帖子是我的leanCloud账号。因为之前一直登陆失败，所以先在github上先提问了。
 原始邮件 
发件人: Jang Rush<notifications@github.com>
收件人: leancloud/lean-cli<lean-cli@noreply.github.com>
抄送: QuanYiZh<zqy157634@hotmail.com>; Author<author@noreply.github.com>
发送时间: 2020年2月10日(周一) 13:29
主题: Re: [leancloud/lean-cli] 0.21.0版本lean up一直提示关于goroutine的错误 (#433)


论坛是通过 leancloud 账号 oauth 登录的。您可以尝试换个浏览器试试。如果仍有问题可以写信给 support at leancloud.rocks 咨询。
https://forum.leancloud.cn/t/mac-lean-lean-up-3001-goroute/22157 <-- 这个帖子是您用其他账号发的吗？

**Comment by papabattery** [comment]
不好意思，真是抱歉。之前的错误发现原因了，是我这边交接的代码被删了部分代码造成的错误，是我这边的原因。
