### ISSUE TITLE
使用更精确的 Region 描述

### ISSUE THREAD

**Issue by leeyeh** [leancloud/lean-cli#437]
现有代码中的 Region 还是使用 `CN` / `TAB` / `US` 来描述，应该替换为更加精确的 `cn-n1` / `cn-e1` / `us-w1`。

其中对用户可见的影响包括 login / switch command 的 region 参数。

**Comment by soasurs** [comment]
计划用 `cn-n1` `cn-e1` `us-w1` 分别替换 `lean-cli` 和用户交互时的区域名称。
