### ISSUE TITLE
当端口 3001 被占用导致本地无法启动时，3000 端口应用没有关闭

### ISSUE THREAD

**Issue by sdjcw** [leancloud/lean-cli#450]
看起来命令行工具先启动云引擎应用并监听 3000 端口，随后启动云函数工具并监听 3001 端口。

如果 3001 端口已被占用，命令行工具会异常退出，但是 3000 端口的云引擎应用并没有关闭退出。

**Comment by soasurs** [comment]
今天又收到了一个相同问题的工单，修复计划提上日程。

**Comment by jysperm** [comment]
很多文档都假设了应用是运行在 3000 上的，向上找可用的端口可能最后的体验并不好，不如退出让用户来指定端口。

debug conosle 的端口确实应该加一个选项。

**Comment by jysperm** [comment]
现在已经可以指定 debug console 的端口了
