### ISSUE TITLE
支持创建 Android / iOS 模版项目

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#46]

**Comment by jysperm** [comment]
我可以考虑再改一改 http://lcinternal-cloud-code-update.leanapp.cn 让它负责提供命令行工具需要的项目模板、检查更新等功能，现在想要加模板还需要改代码 ...

**Comment by aisk** [comment]
@jysperm 可以考虑做一个层级式的模版选择结构，例如：

- start
  - 客户端开发？
    - iOS
    - Android
  - 服务端开发？
    - Python
    - Node.js
    - PHP
    - Java
    - .net

**Comment by sdjcw** [comment]
init 命令引导过程可以添加一步，比如：
1、选择或者创建 app
2、选择客户端或者服务端项目模版
3、列出可用的项目模板
4、创建完成。

**Comment by aisk** [comment]
👍
