### ISSUE TITLE
lean init 增加项目名自定义选项

### ISSUE THREAD

**Issue by qiuyi116** [leancloud/lean-cli#475]
> [ERROR] mkdir ticket: file exists

基于已有应用为另一个分组使用 `lean init` 初始化项目时，由于跟应用同名的目录已经存在会导致失败。考虑将应用名填充为默认项目名，同时可以在初始化前进行修改。

**Comment by jysperm** [comment]
看起来是可以在参数中设置目录名的

https://github.com/leancloud/lean-cli/blob/master/commands/init_action.go#L205

**Comment by jysperm** [comment]
已在 1.0.0 中修改
