### ISSUE TITLE
没有init

### ISSUE THREAD

**Issue by Fgaoxing** [leancloud/lean-cli#507]
我刚下的
![image](https://user-images.githubusercontent.com/92655031/169525208-75fb4edb-0601-4f07-bd01-a57c71ba53d6.png)
Win11

**Comment by Fgaoxing** [comment]
这咋没有init啊

**Comment by Fgaoxing** [comment]
@juvenn

**Comment by cshuaimin** [comment]
您好，原 `lean init` 命令因为和传统 init 类命令行为不一致（如 `git init` 不会创建新文件夹，只会在当前文件夹初始化），已经改为 `lean new` 命令了。

在 1.0 版本中还有一些其他不兼容更改，详见 https://github.com/leancloud/lean-cli/releases/tag/v1.0.0

**Comment by Fgaoxing** [comment]
@cshuaimin 你们的文档和云中没有标明，建议修改
