### ISSUE TITLE
支持部署时的“调试”模式

### ISSUE THREAD

**Issue by aisk** [leancloud/lean-cli#79]
- [ ] 发送请求到 beta.leancloud.cn
- [ ] 允许在调用 buildAndDeploy 时传递自定义参数

**Comment by jysperm** [comment]
>发送请求到 beta.leancloud.cn

可通过 `export LEANCLOUD_DASHBOARD=https://beta.leancloud.cn` 配置

>允许在调用 buildAndDeploy 时传递自定义参数

已在 https://github.com/leancloud/lean-cli/pull/409 中支持
